### ISSUE TITLE
 Error in playercontainer

### ISSUE THREAD

**Issue by Xyphenore** [gigaherz/InventorySpam#12]
We get this as an error 
"Error occurred applying transform of coremod cm/playercontainer-setall-hook.js function InventorySpam PlayerContainer Transformer
jdk.nashorn.internal.runtime.ECMAException: TypeError: method.instructions.addAll is not a function",
 but it doesn't crash the game

**Comment by gigaherz** [comment]
That would be because it just cancels the coremod, so the mod would have trouble detecting items when teleporting across dimensions.

I will look into it as soon as I can, since it worked perfectly fine in my development last time I tried.
To make my job easier: what version of java are you using? the one included in the vanilla launcher? something else? you can see the version in the F3 screen

**Comment by Xyphenore** [comment]
i use always the last version of java, so i use now the version 1.8.0_211
